version: '3.8'

services:
  zabbix-appliance:
    image: zabbix/zabbix-appliance:latest
    container_name: zabbix-appliance
    ports:
      - "8080:8080"   # Porta do frontend
      - "10051:10051" # Porta do servidor Zabbix
    volumes:
      - zabbix_data:/var/lib/zabbix # Volume para persistência de dados
    restart: always

volumes:
  zabbix_data:
